format = """
$username\
$hostname\
$directory\
$jobs\
$character\
"""
right_format = """
$git_branch\
$git_status\
"""

add_newline = false
palette = "catppuccin_mocha"
command_timeout = 1000

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold yellow"

[hostname]
ssh_only = true
format = "[@$hostname]($style)"
trim_at = "-"
style = "bold yellow"

[directory]
truncation_length = 0
truncate_to_repo = false
home_symbol = "~"
format = '[:$path]($style)'
style = 'blue'

[git_branch]
format = '[$branch(:$remote_branch)]($style)'
style = 'mauve'

[git_status]
format = '[ $all_status]($style)'
style = 'mauve'

[jobs]
symbol = "+"
format = "[{$symbol$number}]($style)"
style = "dimmed maroon"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

