format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$jobs\
$character\
"""

add_newline = false
palette = "catppuccin_mocha"
right_format = """$all"""
command_timeout = 1000

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[username]
style_user = "bold dimmed blue"
show_always = true
format = "[$user@]($style)"

[hostname]
ssh_only = false
format = "[$hostname:]($style)"
trim_at = "-"
style = "bold dimmed blue"

[directory]
truncation_length = 0
truncate_to_repo = false
home_symbol = "~"
style = 'blue'
format = '[$path]($style)'

[git_branch]
style = 'mauve'
format = '[\[$branch(:$remote_branch)]($style)'

[git_status]
style = 'mauve'
format = ':[$all_status\]]($style)'

[jobs]
symbol = "+"
style = "dimmed maroon"
format = "[{$symbol$number}]($style)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

